name: Vanderlei Silva's blog
url: http://vanderleisilva.github.io
author: Vanderlei Silva
email: vanderlei.alves.da.silva@gmail.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

baseurl: ""

gems: 
  - jekyll-github-metadata
  - jekyll-multiple-languages-plugin

languages: ['pt', 'en']

exclude_from_localizations: ["_layouts"]