name: Vanderlei Silva's blog
url: http://vanderleisilva.github.io
author: Vanderlei Silva
email: vanderlei.alves.da.silva@gmail.com
telephone: +49 17686314967
address: Ganghoferstra√üe 39, 80339 Munich - Germany 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
baseurl: ""
plugins: ["jekyll-github-metadata", "jekyll-multiple-languages-plugin"]
languages: ['en', 'pt']
exclude_from_localizations: ["css", "fonts", "images", "js"]
destination: docs